### ISSUE TITLE
Kleinkorrekturen am Datenmodell

### ISSUE THREAD

**Issue by uncoyote** [simi-so/simi#13]
PostgresDB
* Default boolean ist zwingend
* $dok rename auf defaultValue

ModelSchema
* $dok UK ohne Modellname

PostgresTable
* $neu UK auf Tabellenname, Schema-FK --> evtl. Datenmodell anpassen

TableField
* $dok constraint anpassen

TableView
* $dok geo übernommen?

PropertiesInList - InFacade
* transp nicht zwingende Angabe

Map
* UK scheint zu fehlen

Global:
* Defaults?
* Kinder ohne Attribute / Beziehungen
  * LayerGroup
  * ExternalTable
* N:M --> FK's nicht nullable
* Update-Scripts unter source-control?

**Comment by patrickackermann** [comment]
Map
- UK auf _wgcUrlValue_ geht nicht so einfach: https://www.cuba-platform.com/discuss/t/inheritance-strategy-and-unique-constraints/1761
